codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

flags:
  plugin-core:
    paths:
      - plugin-core/src/main/
    carryforward: true
  chat-ui:
    paths:
      - plugin-core/chat-ui/src/
    carryforward: true
  mcp-server:
    paths:
      - mcp-server/src/main/
    carryforward: true
  plugin-experimental:
    paths:
      - plugin-experimental/src/main/
    carryforward: true
