package com.github.catatafishen.agentbridge.ui;

import kotlin.text.MatchResult;
import kotlin.text.Regex;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class ChatDataModelTest {

    // ── toolDisplayInfo(name) ───────────────────────────────────────────

    @Test
    void toolDisplayInfo_knownTool_returnsNonNull() {
        ToolInfo info = ChatDataModelKt.toolDisplayInfo("view");
        assertNotNull(info);
    }

    @Test
    void toolDisplayInfo_unknownTool_returnsNull() {
        assertNull(ChatDataModelKt.toolDisplayInfo("totally_nonexistent_tool"));
    }

    @Test
    void toolDisplayInfo_caseInsensitive() {
        ToolInfo lower = ChatDataModelKt.toolDisplayInfo("bash");
        ToolInfo mixed = ChatDataModelKt.toolDisplayInfo("Bash");
        ToolInfo upper = ChatDataModelKt.toolDisplayInfo("BASH");
        assertNotNull(lower);
        assertEquals(lower, mixed);
        assertEquals(lower, upper);
    }

    @Test
    void toolDisplayInfo_specificDisplayNames() {
        assertEquals("Bash", ChatDataModelKt.toolDisplayInfo("bash").getDisplayName());
        assertEquals("View", ChatDataModelKt.toolDisplayInfo("view").getDisplayName());
        assertEquals("Grep", ChatDataModelKt.toolDisplayInfo("grep").getDisplayName());
        assertEquals("Web Search", ChatDataModelKt.toolDisplayInfo("web_search").getDisplayName());
    }

    // ── toolSubtitleKey(name) ───────────────────────────────────────────

    @Test
    void toolSubtitleKey_knownTool_returnsExpectedKey() {
        assertEquals("path", ChatDataModelKt.toolSubtitleKey("read_file"));
        assertEquals("query", ChatDataModelKt.toolSubtitleKey("search_text"));
        assertEquals("target", ChatDataModelKt.toolSubtitleKey("run_tests"));
    }

    @Test
    void toolSubtitleKey_unknownTool_returnsNull() {
        assertNull(ChatDataModelKt.toolSubtitleKey("no_such_tool"));
    }

    // ── QUICK_REPLY_TAG_REGEX ───────────────────────────────────────────

    @Test
    void quickReplyRegex_matchesSimpleTag() {
        Regex regex = ChatDataModelKt.getQUICK_REPLY_TAG_REGEX();
        assertTrue(regex.containsMatchIn("[quick-reply: A | B]"));
    }

    @Test
    void quickReplyRegex_matchesTagWithDismiss() {
        Regex regex = ChatDataModelKt.getQUICK_REPLY_TAG_REGEX();
        assertTrue(regex.containsMatchIn("[quick-reply: Yes | No:dismiss]"));
    }

    @Test
    void quickReplyRegex_doesNotMatchPlainText() {
        Regex regex = ChatDataModelKt.getQUICK_REPLY_TAG_REGEX();
        assertFalse(regex.containsMatchIn("This is just regular text without any tag"));
    }

    @Test
    void quickReplyRegex_capturesContentAfterColon() {
        Regex regex = ChatDataModelKt.getQUICK_REPLY_TAG_REGEX();
        MatchResult match = regex.find("[quick-reply: Option A | Option B]", 0);
        assertNotNull(match);
        // Group 1 captures everything after "quick-reply:" inside the brackets
        String captured = match.getGroupValues().get(1);
        assertTrue(captured.contains("Option A"));
        assertTrue(captured.contains("Option B"));
    }

    // ── EntryData sealed hierarchy ──────────────────────────────────────

    @Test
    void prompt_constructionAndGetters() {
        EntryData.Prompt prompt = new EntryData.Prompt("Hello world", "2025-01-01T00:00:00Z", null, "");
        assertEquals("Hello world", prompt.getText());
        assertEquals("2025-01-01T00:00:00Z", prompt.getTimestamp());
    }

    @Test
    void text_constructionAndGetters() {
        EntryData.Text text = new EntryData.Text("raw content", "2025-01-01T00:00:00Z", "", "gpt-4");
        assertEquals("raw content", text.getRaw());
        assertEquals("gpt-4", text.getModel());
    }

    @Test
    void toolCall_constructionAndSetResult() {
        EntryData.ToolCall toolCall = new EntryData.ToolCall("read_file", "{\"path\": \"foo.txt\"}");
        assertEquals("read_file", toolCall.getTitle());
        assertEquals("{\"path\": \"foo.txt\"}", toolCall.getArguments());
        assertNull(toolCall.getResult());

        toolCall.setResult("file contents here");
        assertEquals("file contents here", toolCall.getResult());
    }

    @Test
    void thinking_construction() {
        EntryData.Thinking thinking = new EntryData.Thinking("thinking about it...", "2025-01-01T00:00:00Z");
        assertEquals("thinking about it...", thinking.getRaw());
        assertEquals("2025-01-01T00:00:00Z", thinking.getTimestamp());
    }

    @Test
    void entryId_autoGenerated_notEmpty() {
        EntryData.Prompt prompt = new EntryData.Prompt("test");
        EntryData.Text text = new EntryData.Text();
        EntryData.ToolCall toolCall = new EntryData.ToolCall("title");
        EntryData.Thinking thinking = new EntryData.Thinking();

        assertNotNull(prompt.getEntryId());
        assertFalse(prompt.getEntryId().isEmpty());
        assertNotNull(text.getEntryId());
        assertFalse(text.getEntryId().isEmpty());
        assertNotNull(toolCall.getEntryId());
        assertFalse(toolCall.getEntryId().isEmpty());
        assertNotNull(thinking.getEntryId());
        assertFalse(thinking.getEntryId().isEmpty());
    }

    @Test
    void entryId_differentEntriesHaveDifferentIds() {
        EntryData.Prompt a = new EntryData.Prompt("one");
        EntryData.Prompt b = new EntryData.Prompt("two");
        EntryData.Text c = new EntryData.Text("three");
        assertNotEquals(a.getEntryId(), b.getEntryId());
        assertNotEquals(a.getEntryId(), c.getEntryId());
    }

    // ── TOOL_DISPLAY_INFO map completeness ──────────────────────────────

    @Test
    void toolDisplayInfo_allEntriesHaveNonNullNameAndDescription() {
        Map<String, ToolInfo> map = ChatDataModelKt.getTOOL_DISPLAY_INFO();
        assertFalse(map.isEmpty());
        for (Map.Entry<String, ToolInfo> entry : map.entrySet()) {
            assertNotNull(entry.getValue().getDisplayName(),
                    "displayName is null for key: " + entry.getKey());
            assertFalse(entry.getValue().getDisplayName().isEmpty(),
                    "displayName is empty for key: " + entry.getKey());
            assertNotNull(entry.getValue().getDescription(),
                    "description is null for key: " + entry.getKey());
            assertFalse(entry.getValue().getDescription().isEmpty(),
                    "description is empty for key: " + entry.getKey());
        }
    }

    @Test
    void toolDisplayInfo_specificToolsArePresent() {
        Map<String, ToolInfo> map = ChatDataModelKt.getTOOL_DISPLAY_INFO();
        assertTrue(map.containsKey("view"), "Expected 'view' in TOOL_DISPLAY_INFO");
        assertTrue(map.containsKey("bash"), "Expected 'bash' in TOOL_DISPLAY_INFO");
        assertTrue(map.containsKey("web_search"), "Expected 'web_search' in TOOL_DISPLAY_INFO");
        assertTrue(map.containsKey("grep"), "Expected 'grep' in TOOL_DISPLAY_INFO");
    }
}
